{
 "title": "New dashboard",
 "time": { "from": "2025-12-11T19:26:42.000Z", "to": "2025-12-11T21:31:58.000Z" },
 "panels": [
  {
   "title": "95-й перцентиль времени ответа",
   "type": "timeseries",
   "description": "Инфраструктурный уровень - производительность",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки 5xx",
   "type": "timeseries",
   "description": "Прикладной уровень - клиентские и серверные ошибки",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_count_total{http_status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки 4xx",
   "type": "timeseries",
   "description": "Прикладной уровень - клиентские и серверные ошибки",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_count_total{http_status=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Частота запросов в минуту",
   "type": "timeseries",
   "description": "Инфраструктурный уровень - нагрузка на сервис",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(request_count_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Распределение предсказаний цен",
   "type": "timeseries",
   "description": "Прикладной уровень - гистограмма предсказаний модели",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "prediction_price_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}