channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==3.5.1
  - catboost==1.2.8
  - ipywidgets==8.1.7
  - numpy==2.2.6
  - pandas==2.3.2
  - scipy==1.15.3
name: mlflow-env
